// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2bR0JLa6dWVSa-qJmtHf73cZnFKBYD2o',
    appId: '1:938770112002:web:61e522b96a894d5e86d11b',
    messagingSenderId: '938770112002',
    projectId: 'fashion-fusion-ed6ac',
    authDomain: 'fashion-fusion-ed6ac.firebaseapp.com',
    storageBucket: 'fashion-fusion-ed6ac.firebasestorage.app',
    measurementId: 'G-V9PSVWVCNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3nDJ88nvoO3scNhX-08AERELooumORXo',
    appId: '1:938770112002:android:9346998ad8e6f85d86d11b',
    messagingSenderId: '938770112002',
    projectId: 'fashion-fusion-ed6ac',
    storageBucket: 'fashion-fusion-ed6ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUwDWDWVtJp7njf0eCwbYZnErjpcU4NI',
    appId: '1:938770112002:ios:03c8a77973036da786d11b',
    messagingSenderId: '938770112002',
    projectId: 'fashion-fusion-ed6ac',
    storageBucket: 'fashion-fusion-ed6ac.firebasestorage.app',
    iosBundleId: 'com.suneel.fashionfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUwDWDWVtJp7njf0eCwbYZnErjpcU4NI',
    appId: '1:938770112002:ios:88fb3f044a26f7f086d11b',
    messagingSenderId: '938770112002',
    projectId: 'fashion-fusion-ed6ac',
    storageBucket: 'fashion-fusion-ed6ac.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2bR0JLa6dWVSa-qJmtHf73cZnFKBYD2o',
    appId: '1:938770112002:web:af0699fd32a55b3c86d11b',
    messagingSenderId: '938770112002',
    projectId: 'fashion-fusion-ed6ac',
    authDomain: 'fashion-fusion-ed6ac.firebaseapp.com',
    storageBucket: 'fashion-fusion-ed6ac.firebasestorage.app',
    measurementId: 'G-3KWSEPP0WQ',
  );
}
